d /run/ops-agent 0755 root root -
d /run/ops-agent/helper 0755 root root -
d /var/lib/ops-agent 0755 root root -
d /var/lib/ops-agent/root-helper 0700 root root -
d /var/lib/ops-agent/pve-root-helper 0700 root root -
d /var/log/ops-agent 0755 root root -
d /var/log/ops-agent/root-helper 0700 root root -
d /var/log/ops-agent/pve-root-helper 0700 root root -
d /etc/ops-agent 0755 root root -
d /etc/ops-agent/tls 0755 root root -
